# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca390d1e77640ac8990200745bf9fb3955d0c02fadc23085182feeb1d396fa1d34a9c5ce9519ae5b016e043fa3c03d2f0a64e8d5e2c3852d3888d228680f187b

test:
  secret_key_base: 6f565a39b0e7f4459d3d03d437e511ceb5b6229975d9ccf0e48ee4c3b2ded24432dc93b6406e0bd1ca037fc93fc3b8db659a7593178188a80d3da5413363a8f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
